/**
 * ufr-invrep-core-api
 * Инвестиционный отчёт
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CurrencyExchangeRate { 
    /**
     * Стоимость доллара на дату окончания за период
     */
    dollarPrice: number;
    /**
     * Стоимость евро на дату окончания за период
     */
    euroPrice: number;
    /**
     * Наименования месяца или квартала
     */
    name: string;
    /**
     * Год
     */
    year: string;
}
