/**
 * ufr-invrep-core-api
 * Инвестиционный отчёт
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { CurrencyExchangeRate } from './currency-exchange-rate';
import { Images } from './images';
import { InvestPortfolio } from './invest-portfolio';
import { PaymentSchedulesTable1 } from './payment-schedules-table-1';
import { PaymentSchedulesTable2 } from './payment-schedules-table-2';
import { PaymentSchedulesTable3 } from './payment-schedules-table-3';
import { Period } from './period';
import { Person } from './person';
import { Portfolio } from './portfolio';
import { Product } from './product';
import { ProductExpirationDate } from './product-expiration-date';
import { Share } from './share';


export interface InvestReportDocRequest { 
    /**
     * Валюты в портфеле
     */
    currencies: Array<Currency>;
    /**
     * Стоимость валют
     */
    currencyExchangeRates: Array<CurrencyExchangeRate>;
    images?: Images;
    /**
     * Движения денежных средств клиента
     */
    investPortfolios: Array<InvestPortfolio>;
    paymentSchedulesTable1?: PaymentSchedulesTable1;
    paymentSchedulesTable2?: PaymentSchedulesTable2;
    paymentSchedulesTable3?: PaymentSchedulesTable3;
    /**
     * Период
     */
    period: Period;
    /**
     * Клиент
     */
    person: Person;
    /**
     * Портфель клиента
     */
    portfolio: Portfolio;
    /**
     * Даты закрытия продуктов
     */
    productExpirationDates?: Array<ProductExpirationDate>;
    /**
     * Продукты клиента
     */
    products?: Array<Product>;
    /**
     * Соотношения активов клиента
     */
    shares: Array<Share>;
}
