/**
 * ufr-invrep-core-api
 * Инвестиционный отчёт
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentSchedules2 } from './payment-schedules-2';
import { Period } from './period';


/**
 * Информация по предстоящим выплатам
 */
export interface PaymentSchedulesTable2 { 
    /**
     * Продукты, по которым предстоят выплаты
     */
    paymentSchedules2: Array<PaymentSchedules2>;
    /**
     * Период
     */
    period: Period;
}
