/**
 * ufr-invrep-core-api
 * Инвестиционный отчёт
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Portfolio { 
    /**
     * Баланс клиента на дату окончания
     */
    balance: string;
    /**
     * Доход портфеля на дату окончания
     */
    income: number;
    /**
     * Доходность в процентах на дату окончания
     */
    incomePercent: number;
    /**
     * Операции снятия/пополнения на дату окончания
     */
    operation: string;
}
