/**
 * ufr-invrep-core-api
 * Инвестиционный отчёт
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Product { 
    /**
     * Средняя цена покупки продукта
     */
    avgPrice?: number;
    /**
     * Сумма купонных выплат за продукт
     */
    coupons?: number;
    /**
     * Процент купонных выплат
     */
    couponsPercent?: string;
    /**
     * Сумма выплаченных дивидендов за продукт
     */
    dividends?: number;
    /**
     * Процент дивидентов
     */
    dividendsPercent?: string;
    /**
     * Доход по продукту
     */
    income: number;
    /**
     * Наименование продукта в портфеле
     */
    name: string;
    /**
     * Дата первой покупки продукта
     */
    openDate?: string;
    /**
     * Процентное соотношение продукта к остальным продуктам в портфеле
     */
    part: number;
    /**
     * Процент дохода
     */
    percent: string;
    /**
     * Цена за один продукт на дату окончания
     */
    price?: number;
    /**
     * Количество продукта в портфеле
     */
    quantity: number;
    /**
     * Общая сумма продукта в портфеле
     */
    totalAmount: number;
}
